# Add feature toggles with the format:
# <feature_name>: off|dev|release
show_licensing_overview_success_rate: release
show_licensing_visitors_realtime: release
show_fco_visitors_realtime: dev
fco_dashboards: dev
hmrc_dashboards: dev
lpa_dashboard: dev
lpa_dashboard_application_method: dev
show_fco_availability: dev
show_lpa_availability: release
lpa_conversion_funnel: dev
evl_dashboard: dev
evl_availability_modules: dev
